### ISSUE TITLE
 js error: $(...).modal is not a function...

### ISSUE THREAD

**Issue by huangjian80s** [richardfan1126/yii2-sortable-gridview#1]
hello!
I like yii2 and i am newcomer (and me english is bad ,sorry!)
I use composer to install,complete!
It has some error,so i add js and css by manaul,
like this
`<?=Html::jsFile('@web/myjs/jQuery.js')?>
<?=Html::jsFile('@web/js/bootstrap.js')?>
<?=Html::cssFile('@web/css/bootstrap.css')?>`
and use $(...).modal("show");,is ok,
![image](https://cloud.githubusercontent.com/assets/11827644/16657224/4982c850-4494-11e6-88e2-b72cb3cddd44.png)

But,I sort list,chrome still reports error:$(...).modal is not a function...
I can sort list
![image](https://cloud.githubusercontent.com/assets/11827644/16657712/08c755f4-4496-11e6-997c-1ad13dafa634.png)

I need your help,thank!

Last,I dont not know how change data of database by sort,i think your extension should be use ajax,but your extension not config ajax(i mean sortUrl,sortingPromptText,failText),can you tell me how?
Thank you for your help,thank!

**Comment by huangjian80s** [comment]
ok,today i has solved the issue,and i has pull requests,now please close this issue
Lastly,thank for your work,thank

**Comment by richardfan1126** [comment]
Thank you for your suggestion,
I have missed adding Bootstrap asset into the plugin,
I will add back the yii bootstrap asset into it, I think it would be better than put bootstrap files directly into it.
