### ISSUE TITLE
Doc: How to add a column with a drag icon

### ISSUE THREAD

**Issue by sokollondon** [richardfan1126/yii2-sortable-gridview#19]
![2019-09-12_14-32-12](https://user-images.githubusercontent.com/11624566/64774320-6ab66280-d56d-11e9-82e1-e8461e339123.png)

    'columns' => [
        [
            'content'=>function(){ return "<span class='glyphicon glyphicon-resize-vertical'></span>";},
            'contentOptions' => ['style'=>'width: 34px; cursor:move;'],
        ],
        //...
    ],

Add this to the documentation. This is necessary because users don’t understand that rows can be dragged =)

**Comment by loveshenshen** [comment]
How to make it work on Pad or Phone .

**Comment by wa1kb0y** [comment]
pull request #23 added it, issue can be closed
