### ISSUE TITLE
Error when used SerialColumn and ActionColumn

### ISSUE THREAD

**Issue by kongoon** [richardfan1126/yii2-sortable-gridview#4]
How to fix when used grid SerialColumn and ActionColumn?

**Comment by richardfan1126** [comment]
There is a bugfix in v0.0.4, try using it to see if it works

**Comment by pptyasar** [comment]
Is ActionColumn can be used? @richardfan1126

**Comment by richardfan1126** [comment]
@pptyasar 
Yes, you can add ActionColumn into the GridView

**Comment by pptyasar** [comment]
Showing error as `Setting unknown property: richardfan\sortable\SortableGridView::0`

**Comment by pptyasar** [comment]
Sorry its my mistke I place `            ['class' => 'yii\grid\ActionColumn']
` after columns
